//
// system_top.v — auto-generated by zynq_mcp pl_generate_system_top
// DO NOT EDIT
//
module system_top
  (clk_in,
   reset_n,
   led_pins,
   data_in,
   data_out
  );
  input clk_in;
  input reset_n;
  output [3:0] led_pins;
  input [7:0] data_in;
  output [7:0] data_out;

  wire clk_in;
  wire reset_n;
  wire [3:0] led_pins;
  wire [7:0] data_in;
  wire [7:0] data_out;

  design_1_wrapper design_1_wrapper_i
       (.clk_in(clk_in),
        .reset_n(reset_n),
        .led_pins(led_pins),
        .data_in(data_in),
        .data_out(data_out)
       );
endmodule
